import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import style from "../src/style.module.css"

export default function Home() {

  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS lesson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <Link href='/notes'>
       for notes page
      </Link>
      <br/>
      <h1>for dynamic path</h1>
      <br/>
      
      <Link href='/notes/[id]' as= {`/notes/${1}`} >
      
      Note 1 

      </Link>
      <br/>
      <button onClick={e=>router.push('/notes')} >programic routing</button>
      <button onClick={e=>router.push(`/notes/[id]`,`/notes/${e.target.tagName}`)} >1</button>

      <button onClick={e=>console.log(e)} >2</button>
      <button onClick={e=>router.push(`/notes/[id]`,`/notes/${e.target.tagName}`)} >3</button>
      <button onClick={e=>router.push(`/notes/[id]`,`/notes/${e.target.tagName}`)} >4</button>
      <div>
        <a href={process.env.HELP_APP_URL} >test env here</a>
      </div>

    </div>
  )
}
